### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by vladikdomniuk** [vladikdomniuk/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by killenemy** [comment]
Я актор з 23-річним акторським стажем, який підніме кількість переглядів ваших фільмів на новий рівень, оскільки маю величезне коло шанувальників через свою неперевершену гру, харизму та чудову фізичну форму

**Comment by vladikdomniuk** [comment]
Good
