### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by vladikdomniuk** [vladikdomniuk/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by killenemy** [comment]
facebook: https://www.facebook.com/JasonStatham  
instagram: https://instagram.com/jasonstatham?igshid=1wz93p2s2idf1

**Comment by vladikdomniuk** [comment]
Good
