### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by vladikdomniuk** [vladikdomniuk/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by vladikdomniuk** [comment]
Початок кар'єри(Біографія):
Кар'єру моделі успішно поєднував із роботою на вулиці, де збував крадені чи підроблені товари.  Режисера заінтригувало моє темне минуле та вразила моя модельна робота. Мене було запрошено на проби, а  замість етюду запропонувано зобразити вуличного торговця й переконати купити гарнітур підроблених золотих   коштовностей. Ґаєві був потрібен справжній характер. І це був я, тому що таких речей не вчать у драматичній школі. Мені вдалося продати Ґаю Річі нічого не вартий товар, а коли той спробував повернути його, я проявив таку непохитність, що Річі негайно взяв мене на роль.

**Comment by killenemy** [comment]
Початок кар'єри(Біографія):
Кар'єру моделі успішно поєднував із роботою на вулиці, де збував крадені чи підроблені товари. Режисера заінтригувало моє темне минуле та вразила моя модельна робота. Мене було запрошено на проби, а замість етюду запропонувано зобразити вуличного торговця й переконати купити гарнітур підроблених золотих коштовностей. Ґаєві був потрібен справжній характер. І це був я, тому що таких речей не вчать у драматичній школі. Мені вдалося продати Ґаю Річі нічого не вартий товар, а коли той спробував повернути його, я проявив таку непохитність, що Річі негайно взяв мене на роль.

**Comment by vladikdomniuk** [comment]
Good
