### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by vladikdomniuk** [vladikdomniuk/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by killenemy** [comment]
Касові збори(Біографія):
Починаючи з 1998 року, я знімався у більш ніж двадцяти фільмах. Деякі з них мали комерційний успіх, наприклад «Великий куш» і серія Форсаж. Він був головним героєм у таких серіях фільмів, як «Перевізник» та «Адреналін». Сумарно фільми, в яких я знімався, зібрали більше $5 мільярда, а найбільші збори були у фільму «Форсаж 8».

**Comment by vladikdomniuk** [comment]
Good
